[pytest]
addopts =
    --ignore=app/modules/reports/test_reports.py
    --ignore=app/db/test_db.py
    --ignore=app/modules/events/test_create_event.py
    --ignore=app/modules/events/test_event_lifecycle.py
    --ignore=app/modules/events/test_food_pass.py
    --ignore=app/modules/ledger/test_ledger.py
    --ignore=app/modules/payments/test_payment.py
    --ignore=app/modules/payments/test_refund.py
    --ignore=app/whatsapp/test_whatsapp.py
pythonpath = .
