ALTER TABLE announcements
    ADD COLUMN IF NOT EXISTS total_targets INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS sent_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS failed_count INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS skipped_count INTEGER NOT NULL DEFAULT 0;
