#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Fri Jan 23 17:33:32 2026

@author: anonymous
"""

from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.lib.units import cm
from reportlab.lib.utils import ImageReader
from reportlab.lib import colors
from reportlab.lib.colors import HexColor
from reportlab.platypus import Paragraph, Spacer, Table, TableStyle, Image
from reportlab.pdfgen import canvas
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.ttfonts import TTFont
from datetime import datetime
import os


class BasePDF:
    def __init__(self, buffer, society_name, report_title, logo_path=None):
        pdfmetrics.registerFont(
            TTFont("DejaVu", "app/assets/fonts/DejaVuSans.ttf")
        )
        self.buffer = buffer
        self.society_name = society_name
        self.report_title = report_title
        self.logo_path = logo_path
        self.width, self.height = A4
        self.styles = getSampleStyleSheet()


    def header_footer(self, canvas: canvas.Canvas, page_num: int):
# =============================================================================
#         
#         # Header background
#         c.setFillColor(colors.HexColor("#2E7D32"))
#         c.rect(0, self.height - 3 * cm, self.width, 3 * cm, fill=1)
#     
#         x_offset = 2 * cm
#     
#         # Logo (if exists)
#         if self.logo_path and os.path.exists(self.logo_path):
#             logo = ImageReader(self.logo_path)
#             c.drawImage(
#                 logo,
#                 x_offset,
#                 self.height - 2.6 * cm,
#                 width=1.8 * cm,
#                 height=1.8 * cm,
#                 mask="auto"
#             )
#             x_offset += 2.2 * cm
#     
#         # Society name
#         c.setFillColor(colors.white)
#         c.setFont("DejaVu", 14)
#         c.drawString(x_offset, self.height - 2 * cm, self.society_name)
#     
#         # Report title
#         c.setFont("DejaVu", 10)
#         c.drawRightString(
#             self.width - 2 * cm,
#             self.height - 2 * cm,
#             self.report_title
#         )
#     
#         # Footer
#         c.setFillColor(colors.grey)
#         c.setFont("DejaVu", 8)
#         c.drawString(2 * cm, 1.5 * cm, "Generated by Society Agent")
#         c.drawCentredString(self.width / 2, 1.5 * cm, f"Page {page_num}")
#         c.drawRightString(
#             self.width - 2 * cm,
#             1.5 * cm,
#             "Confidential – For Society Use Only"
#         )
# =============================================================================

        width, height = canvas._pagesize

        # ---------- GREEN HEADER BAR ----------
        canvas.setFillColor(HexColor("#1f7a4f"))
        canvas.rect(0, height - 80, width, 80, stroke=0, fill=1)

        # ---------- SOCIETY NAME ----------
        canvas.setFillColorRGB(1, 1, 1)
        canvas.setFont("DejaVu", 14)
        canvas.drawString(40, height - 45, self.society_name)

        # ---------- REPORT TITLE ----------
        canvas.setFont("DejaVu", 11)
        canvas.drawString(40, height - 65, self.report_title)

        # ---------- LOGO (RIGHT SIDE) ----------
        if self.logo_path and os.path.exists(self.logo_path):
            try:
                canvas.drawImage(
                    self.logo_path,
                    width - 120,
                    height - 70,
                    width=60,
                    height=60,
                    preserveAspectRatio=True,
                    mask="auto"
                )
            except Exception:
                pass  # logo should never break PDF

        # ---------- FOOTER ----------
# =============================================================================
#         canvas.setFont("DejaVu", 9)
#         canvas.setFillColorRGB(0, 0, 0)
#         canvas.drawRightString(
#             width - 40,
#             30,
#             f"Page {page_num}"
#         )
# =============================================================================
        canvas.setFillColor(colors.grey)
        canvas.setFont("DejaVu", 8)
        canvas.drawString(2 * cm, 1.5 * cm, "Generated by Society Agent")
        canvas.drawCentredString(width / 2, 1.5 * cm, f"Page {page_num}")
        canvas.drawRightString(
            width - 2 * cm,
            1.5 * cm,
            "Confidential – For Society Use Only"
        )
        

# =============================================================================
#     def report_meta(self, elements, meta: dict):
#         box_style = self.styles["Normal"]
#         box_style.fontName = "DejaVu"
#         box_style.backColor = colors.whitesmoke
#         box_style.spaceAfter = 6
#         box_style.leftIndent = 6
#     
#         elements.append(Spacer(1, 12))
#         for key, value in meta.items():
#             elements.append(
#                 Paragraph(f"<b>{key}:</b> {value}", box_style)
#             )
#         elements.append(Spacer(1, 16))
# =============================================================================
        
    def report_meta(self, elements, meta: dict):
        from reportlab.platypus import Paragraph, Spacer
        from reportlab.lib.styles import getSampleStyleSheet

        styles = getSampleStyleSheet()

        for k, v in meta.items():
            elements.append(
                Paragraph(f"<b>{k}:</b> {v}", styles["Normal"])
            )
        elements.append(Spacer(1, 12))


    def summary_box(self, title: str, rows: list):
        data = [[title, ""]] + rows
    
        table = Table(data, colWidths=[8 * cm, 6 * cm])
        table.setStyle(TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#E3F2FD")),
            ("SPAN", (0, 0), (-1, 0)),
            ("FONT", (0, 0), (-1, 0), "DejaVu"),
            ("FONT", (0, 1), (-1, -1), "DejaVu"),
            ("GRID", (0, 0), (-1, -1), 0.25, colors.grey),
            ("ALIGN", (1, 1), (-1, -1), "RIGHT"),
            ("LEFTPADDING", (0, 0), (-1, -1), 8),
            ("TOPPADDING", (0, 0), (-1, -1), 6),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ]))
        return table

