#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Centralized constants for WhatsApp channel integration."""

# Environment variable keys
WHATSAPP_VERIFY_TOKEN_ENV_KEY = "WHATSAPP_VERIFY_TOKEN"
WHATSAPP_APP_SECRET_ENV_KEY = "WHATSAPP_APP_SECRET"
WHATSAPP_ACCESS_TOKEN_ENV_KEY = "WHATSAPP_ACCESS_TOKEN"
WHATSAPP_PHONE_NUMBER_ID_ENV_KEY = "WHATSAPP_PHONE_NUMBER_ID"
WHATSAPP_API_VERSION_ENV_KEY = "WHATSAPP_API_VERSION"
WHATSAPP_GRAPH_BASE_URL_ENV_KEY = "WHATSAPP_GRAPH_BASE_URL"

# API defaults
DEFAULT_WHATSAPP_API_VERSION = "v22.0"
DEFAULT_WHATSAPP_GRAPH_BASE_URL = "https://graph.facebook.com"
WHATSAPP_REQUEST_TIMEOUT_SECONDS = 10

# API constants
WHATSAPP_MESSAGING_PRODUCT = "whatsapp"
WHATSAPP_MESSAGES_PATH = "messages"
WHATSAPP_SIGNATURE_HEADER = "X-Hub-Signature-256"
WHATSAPP_WEBHOOK_VERIFY_MODE_SUBSCRIBE = "subscribe"
